name: apk

on: 
  push:
    branches: [ master ]
    workflow: tests

jobs:
    apk:
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/${{ github.repository }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }
      steps:
        - uses: actions/checkout@v3
          with: 
            submodules: true
        - name: make apk
          env:
            TAILSCALE_SERVER: ${{ secrets.TAILSCALE_SERVER }}
          run: |
            make patch
            make apk
        - name: save apk artifact
          uses: actions/upload-artifact@v3
          with:
           name: apk
           path: tailscale-android/tailscale-debug.apk
